### ISSUE TITLE
SQLSTATE[23502]: Not null violation

### ISSUE THREAD

**Issue by MushfiqueAhmed027** [csesumonpro/Laravel-roles-permission-middlewae#1]
can't register the registration form.The error is shown below:
Illuminate\Database\QueryException
SQLSTATE[23502]: Not null violation: 7 ERROR: null value in column "role_id" violates not-null constraint DETAIL: Failing row contains (3, admin1, admin1@admin.com, null, $2y$10$6LB8cxbVOZvpSDLwJ0NiV.Hq.0C2poE2mnf.BZYyPIlraoub/hZ8u, null, null, 2020-04-21 11:52:41, 2020-04-21 11:52:41). (SQL: insert into "users" ("name", "email", "password", "updated_at", "created_at") values (admin1, admin1@admin.com, $2y$10$6LB8cxbVOZvpSDLwJ0NiV.Hq.0C2poE2mnf.BZYyPIlraoub/hZ8u, 2020-04-21 11:52:41, 2020-04-21 11:52:41) returning "id")

**Comment by csesumonpro** [comment]
This is a simple problem. It's a nullable problem. If you want to save the null value in your database must need to set nullable in your migration file. After then execute a fresh migrate. Otherwise must need to set a default value.  After a fresh migration just run php artisan db:seed because of I have already make a seeder for create a user for initial situation.
